/**
 * A real, human-curated 2026 Superflex/2QB PPR consensus ranking snapshot
 * (FantasyPros), pasted in directly by the user. Used two ways:
 *
 *  1. Real ADP for any Sleeper-synced player it covers — far more reliable
 *     than Sleeper's own `search_rank` proxy, which is what let a clearly
 *     retired player slip past the relevance cutoff (search_rank isn't
 *     reliably cleared for everyone no longer playing, same story as the
 *     `active` flag).
 *  2. The primary relevance filter for Sleeper-sourced players: someone not
 *     in this list is excluded from the board outright (see
 *     `isInReferenceList` and its use in war-room.tsx), rather than relying
 *     on a numeric cutoff against Sleeper's own possibly-stale signal. This
 *     is real human judgment about who's actually fantasy-relevant right
 *     now, not a proxy for it.
 *
 * This is a point-in-time snapshot, not a live feed — it will drift as the
 * season goes (trades, depth-chart shakeups, cuts, waiver darlings). Paste
 * an updated list and ask to regenerate this file to refresh it. Team
 * abbreviations here are exactly as scraped from the source and are NOT
 * used to override a Sleeper-synced player's own (live, more reliable)
 * team — matching against this list is by player name only.
 */

import { normalizeName } from "./imports";
import type { Position } from "./types";

export type ReferenceRankingEntry = {
  rank: number;
  name: string;
  position: Position;
  team: string;
};

export const REFERENCE_RANKINGS: ReferenceRankingEntry[] = [
  { rank: 1, name: "Josh Allen", position: "QB", team: "BUF" },
  { rank: 2, name: "Lamar Jackson", position: "QB", team: "BAL" },
  { rank: 3, name: "Drake Maye", position: "QB", team: "NE" },
  { rank: 4, name: "Joe Burrow", position: "QB", team: "CIN" },
  { rank: 5, name: "Jayden Daniels", position: "QB", team: "WAS" },
  { rank: 6, name: "Ja'Marr Chase", position: "WR", team: "CIN" },
  { rank: 7, name: "Jalen Hurts", position: "QB", team: "PHI" },
  { rank: 8, name: "Caleb Williams", position: "QB", team: "CHI" },
  { rank: 9, name: "Jahmyr Gibbs", position: "RB", team: "DET" },
  { rank: 10, name: "Justin Herbert", position: "QB", team: "LAC" },
  { rank: 11, name: "Puka Nacua", position: "WR", team: "LAR" },
  { rank: 12, name: "Bijan Robinson", position: "RB", team: "ATL" },
  { rank: 13, name: "Jaxon Smith-Njigba", position: "WR", team: "SEA" },
  { rank: 14, name: "Amon-Ra St. Brown", position: "WR", team: "DET" },
  { rank: 15, name: "Trevor Lawrence", position: "QB", team: "JAC" },
  { rank: 16, name: "Dak Prescott", position: "QB", team: "DAL" },
  { rank: 17, name: "CeeDee Lamb", position: "WR", team: "DAL" },
  { rank: 18, name: "Christian McCaffrey", position: "RB", team: "SF" },
  { rank: 19, name: "Justin Jefferson", position: "WR", team: "MIN" },
  { rank: 20, name: "Brock Purdy", position: "QB", team: "SF" },
  { rank: 21, name: "Jaxson Dart", position: "QB", team: "NYG" },
  { rank: 22, name: "Drake London", position: "WR", team: "ATL" },
  { rank: 23, name: "Bo Nix", position: "QB", team: "DEN" },
  { rank: 24, name: "Jonathan Taylor", position: "RB", team: "IND" },
  { rank: 25, name: "Patrick Mahomes II", position: "QB", team: "KC" },
  { rank: 26, name: "A.J. Brown", position: "WR", team: "NE" },
  { rank: 27, name: "Matthew Stafford", position: "QB", team: "LAR" },
  { rank: 28, name: "Ashton Jeanty", position: "RB", team: "LV" },
  { rank: 29, name: "Nico Collins", position: "WR", team: "HOU" },
  { rank: 30, name: "Jared Goff", position: "QB", team: "DET" },
  { rank: 31, name: "James Cook III", position: "RB", team: "BUF" },
  { rank: 32, name: "Chase Brown", position: "RB", team: "CIN" },
  { rank: 33, name: "Chris Olave", position: "WR", team: "NO" },
  { rank: 34, name: "Brock Bowers", position: "TE", team: "LV" },
  { rank: 35, name: "George Pickens", position: "WR", team: "DAL" },
  { rank: 36, name: "Trey McBride", position: "TE", team: "ARI" },
  { rank: 37, name: "Kyler Murray", position: "QB", team: "MIN" },
  { rank: 38, name: "De'Von Achane", position: "RB", team: "MIA" },
  { rank: 39, name: "Rashee Rice", position: "WR", team: "KC" },
  { rank: 40, name: "DeVonta Smith", position: "WR", team: "PHI" },
  { rank: 41, name: "Malik Nabers", position: "WR", team: "NYG" },
  { rank: 42, name: "Saquon Barkley", position: "RB", team: "PHI" },
  { rank: 43, name: "Omarion Hampton", position: "RB", team: "LAC" },
  { rank: 44, name: "Kenneth Walker III", position: "RB", team: "KC" },
  { rank: 45, name: "Baker Mayfield", position: "QB", team: "TB" },
  { rank: 46, name: "Jordan Love", position: "QB", team: "GB" },
  { rank: 47, name: "Garrett Wilson", position: "WR", team: "NYJ" },
  { rank: 48, name: "Zay Flowers", position: "WR", team: "BAL" },
  { rank: 49, name: "Tyler Shough", position: "QB", team: "NO" },
  { rank: 50, name: "Tetairoa McMillan", position: "WR", team: "CAR" },
  { rank: 51, name: "Jaylen Waddle", position: "WR", team: "DEN" },
  { rank: 52, name: "Ladd McConkey", position: "WR", team: "LAC" },
  { rank: 53, name: "Tee Higgins", position: "WR", team: "CIN" },
  { rank: 54, name: "Malik Willis", position: "QB", team: "MIA" },
  { rank: 55, name: "Colston Loveland", position: "TE", team: "CHI" },
  { rank: 56, name: "Derrick Henry", position: "RB", team: "BAL" },
  { rank: 57, name: "Emeka Egbuka", position: "WR", team: "TB" },
  { rank: 58, name: "Jeremiyah Love", position: "RB", team: "ARI" },
  { rank: 59, name: "Breece Hall", position: "RB", team: "NYJ" },
  { rank: 60, name: "Kyren Williams", position: "RB", team: "LAR" },
  { rank: 61, name: "Sam Darnold", position: "QB", team: "SEA" },
  { rank: 62, name: "C.J. Stroud", position: "QB", team: "HOU" },
  { rank: 63, name: "Javonte Williams", position: "RB", team: "DAL" },
  { rank: 64, name: "Josh Jacobs", position: "RB", team: "GB" },
  { rank: 65, name: "Terry McLaurin", position: "WR", team: "WAS" },
  { rank: 66, name: "Luther Burden III", position: "WR", team: "CHI" },
  { rank: 67, name: "Daniel Jones", position: "QB", team: "IND" },
  { rank: 68, name: "Travis Etienne Jr.", position: "RB", team: "NO" },
  { rank: 69, name: "Cam Ward", position: "QB", team: "TEN" },
  { rank: 70, name: "Davante Adams", position: "WR", team: "LAR" },
  { rank: 71, name: "DJ Moore", position: "WR", team: "BUF" },
  { rank: 72, name: "Tyler Warren", position: "TE", team: "IND" },
  { rank: 73, name: "Mike Evans", position: "WR", team: "SF" },
  { rank: 74, name: "Jameson Williams", position: "WR", team: "DET" },
  { rank: 75, name: "Bryce Young", position: "QB", team: "CAR" },
  { rank: 76, name: "Cam Skattebo", position: "RB", team: "NYG" },
  { rank: 77, name: "Rome Odunze", position: "WR", team: "CHI" },
  { rank: 78, name: "D'Andre Swift", position: "RB", team: "CHI" },
  { rank: 79, name: "Christian Watson", position: "WR", team: "GB" },
  { rank: 80, name: "Bucky Irving", position: "RB", team: "TB" },
  { rank: 81, name: "David Montgomery", position: "RB", team: "HOU" },
  { rank: 82, name: "Quinshon Judkins", position: "RB", team: "CLE" },
  { rank: 83, name: "Jacoby Brissett", position: "QB", team: "ARI" },
  { rank: 84, name: "Parker Washington", position: "WR", team: "JAC" },
  { rank: 85, name: "Carnell Tate", position: "WR", team: "TEN" },
  { rank: 86, name: "TreVeyon Henderson", position: "RB", team: "NE" },
  { rank: 87, name: "Marvin Harrison Jr.", position: "WR", team: "ARI" },
  { rank: 88, name: "Bhayshul Tuten", position: "RB", team: "JAC" },
  { rank: 89, name: "Jadarian Price", position: "RB", team: "SEA" },
  { rank: 90, name: "Harold Fannin Jr.", position: "TE", team: "CLE" },
  { rank: 91, name: "Brian Thomas Jr.", position: "WR", team: "JAC" },
  { rank: 92, name: "Jaylen Warren", position: "RB", team: "PIT" },
  { rank: 93, name: "Tucker Kraft", position: "TE", team: "GB" },
  { rank: 94, name: "Chris Godwin Jr.", position: "WR", team: "TB" },
  { rank: 95, name: "Kyle Pitts Sr.", position: "TE", team: "ATL" },
  { rank: 96, name: "DK Metcalf", position: "WR", team: "PIT" },
  { rank: 97, name: "Rhamondre Stevenson", position: "RB", team: "NE" },
  { rank: 98, name: "Michael Pittman Jr.", position: "WR", team: "PIT" },
  { rank: 99, name: "Courtland Sutton", position: "WR", team: "DEN" },
  { rank: 100, name: "Sam LaPorta", position: "TE", team: "DET" },
  { rank: 101, name: "Tony Pollard", position: "RB", team: "TEN" },
  { rank: 102, name: "Wan'Dale Robinson", position: "WR", team: "TEN" },
  { rank: 103, name: "Geno Smith", position: "QB", team: "NYJ" },
  { rank: 104, name: "Josh Downs", position: "WR", team: "IND" },
  { rank: 105, name: "Rico Dowdle", position: "RB", team: "PIT" },
  { rank: 106, name: "Michael Wilson", position: "WR", team: "ARI" },
  { rank: 107, name: "Aaron Rodgers", position: "QB", team: "PIT" },
  { rank: 108, name: "RJ Harvey", position: "RB", team: "DEN" },
  { rank: 109, name: "Jonathon Brooks", position: "RB", team: "CAR" },
  { rank: 110, name: "Chuba Hubbard", position: "RB", team: "CAR" },
  { rank: 111, name: "Travis Kelce", position: "TE", team: "KC" },
  { rank: 112, name: "Quentin Johnston", position: "WR", team: "LAC" },
  { rank: 113, name: "Alec Pierce", position: "WR", team: "IND" },
  { rank: 114, name: "Kenny Gainwell", position: "RB", team: "TB" },
  { rank: 115, name: "Jakobi Meyers", position: "WR", team: "JAC" },
  { rank: 116, name: "J.K. Dobbins", position: "RB", team: "DEN" },
  { rank: 117, name: "George Kittle", position: "TE", team: "SF" },
  { rank: 118, name: "Stefon Diggs", position: "WR", team: "WAS" },
  { rank: 119, name: "Jayden Reed", position: "WR", team: "GB" },
  { rank: 120, name: "Jordan Addison", position: "WR", team: "MIN" },
  { rank: 121, name: "Makai Lemon", position: "WR", team: "PHI" },
  { rank: 122, name: "Rachaad White", position: "RB", team: "WAS" },
  { rank: 123, name: "Blake Corum", position: "RB", team: "LAR" },
  { rank: 124, name: "Kyle Monangai", position: "RB", team: "CHI" },
  { rank: 125, name: "Jake Ferguson", position: "TE", team: "DAL" },
  { rank: 126, name: "Dalton Kincaid", position: "TE", team: "BUF" },
  { rank: 127, name: "Aaron Jones Sr.", position: "RB", team: "MIN" },
  { rank: 128, name: "Jacory Croskey-Merritt", position: "RB", team: "WAS" },
  { rank: 129, name: "Jordan Mason", position: "RB", team: "MIN" },
  { rank: 130, name: "Isaiah Likely", position: "TE", team: "NYG" },
  { rank: 131, name: "Khalil Shakir", position: "WR", team: "BUF" },
  { rank: 132, name: "Jordyn Tyson", position: "WR", team: "NO" },
  { rank: 133, name: "Dallas Goedert", position: "TE", team: "PHI" },
  { rank: 134, name: "KC Concepcion", position: "WR", team: "CLE" },
  { rank: 135, name: "Jalen Coker", position: "WR", team: "CAR" },
  { rank: 136, name: "Xavier Worthy", position: "WR", team: "KC" },
  { rank: 137, name: "Fernando Mendoza", position: "QB", team: "LV" },
  { rank: 138, name: "Matthew Golden", position: "WR", team: "GB" },
  { rank: 139, name: "Mark Andrews", position: "TE", team: "BAL" },
  { rank: 140, name: "Romeo Doubs", position: "WR", team: "NE" },
  { rank: 141, name: "Juwan Johnson", position: "TE", team: "NO" },
  { rank: 142, name: "Chris Rodriguez Jr.", position: "RB", team: "JAC" },
  { rank: 143, name: "Tyler Allgeier", position: "RB", team: "ARI" },
  { rank: 144, name: "Woody Marks", position: "RB", team: "HOU" },
  { rank: 145, name: "Tyrone Tracy Jr.", position: "RB", team: "NYG" },
  { rank: 146, name: "Tyjae Spears", position: "RB", team: "TEN" },
  { rank: 147, name: "Tua Tagovailoa", position: "QB", team: "ATL" },
  { rank: 148, name: "Dylan Sampson", position: "RB", team: "CLE" },
  { rank: 149, name: "De'Zhaun Stribling", position: "WR", team: "SF" },
  { rank: 150, name: "Deebo Samuel Sr.", position: "WR", team: "SF" },
  { rank: 151, name: "Zach Charbonnet", position: "RB", team: "SEA" },
  { rank: 152, name: "Denzel Boston", position: "WR", team: "CLE" },
  { rank: 153, name: "Keaton Mitchell", position: "RB", team: "LAC" },
  { rank: 154, name: "Rashid Shaheed", position: "WR", team: "SEA" },
  { rank: 155, name: "Chig Okonkwo", position: "TE", team: "WAS" },
  { rank: 156, name: "Brenton Strange", position: "TE", team: "JAC" },
  { rank: 157, name: "Alvin Kamara", position: "RB", team: "NO" },
  { rank: 158, name: "Isiah Pacheco", position: "RB", team: "DET" },
  { rank: 159, name: "Hunter Henry", position: "TE", team: "NE" },
  { rank: 160, name: "Jonah Coleman", position: "RB", team: "DEN" },
  { rank: 161, name: "Jauan Jennings", position: "WR", team: "MIN" },
  { rank: 162, name: "Tank Bigsby", position: "RB", team: "PHI" },
  { rank: 163, name: "Dalton Schultz", position: "TE", team: "HOU" },
  { rank: 164, name: "Jerry Jeudy", position: "WR", team: "CLE" },
  { rank: 165, name: "Tre Tucker", position: "WR", team: "LV" },
  { rank: 166, name: "Adonai Mitchell", position: "WR", team: "NYJ" },
  { rank: 167, name: "Jalen McMillan", position: "WR", team: "TB" },
  { rank: 168, name: "Brian Robinson Jr.", position: "RB", team: "ATL" },
  { rank: 169, name: "Braelon Allen", position: "RB", team: "NYJ" },
  { rank: 170, name: "Tre' Harris", position: "WR", team: "LAC" },
  { rank: 171, name: "Oronde Gadsden II", position: "TE", team: "LAC" },
  { rank: 172, name: "Omar Cooper Jr.", position: "WR", team: "NYJ" },
  { rank: 173, name: "T.J. Hockenson", position: "TE", team: "MIN" },
  { rank: 174, name: "Travis Hunter", position: "WR", team: "JAC" },
  { rank: 175, name: "Michael Penix Jr.", position: "QB", team: "ATL" },
  { rank: 176, name: "Jalen Nailor", position: "WR", team: "LV" },
  { rank: 177, name: "Kirk Cousins", position: "QB", team: "LV" },
  { rank: 178, name: "Ryan Flournoy", position: "WR", team: "DAL" },
  { rank: 179, name: "Malik Washington", position: "WR", team: "MIA" },
  { rank: 180, name: "Dontayvion Wicks", position: "WR", team: "PHI" },
  { rank: 181, name: "Ray Davis", position: "RB", team: "BUF" },
  { rank: 182, name: "Pat Bryant", position: "WR", team: "DEN" },
  { rank: 183, name: "MarShawn Lloyd", position: "RB", team: "GB" },
  { rank: 184, name: "AJ Barner", position: "TE", team: "SEA" },
  { rank: 185, name: "Sean Tucker", position: "RB", team: "TB" },
  { rank: 186, name: "Deshaun Watson", position: "QB", team: "CLE" },
  { rank: 187, name: "Jaylin Noel", position: "WR", team: "HOU" },
  { rank: 188, name: "Emmett Johnson", position: "RB", team: "KC" },
  { rank: 189, name: "Kayshon Boutte", position: "WR", team: "NE" },
  { rank: 190, name: "Calvin Ridley", position: "WR", team: "TEN" },
  { rank: 191, name: "Tank Dell", position: "WR", team: "HOU" },
  { rank: 192, name: "Kimani Vidal", position: "RB", team: "LAC" },
  { rank: 193, name: "Mike Washington Jr.", position: "RB", team: "LV" },
  { rank: 194, name: "Nicholas Singleton", position: "RB", team: "TEN" },
  { rank: 195, name: "Gunnar Helm", position: "TE", team: "TEN" },
  { rank: 196, name: "James Conner", position: "RB", team: "ARI" },
  { rank: 197, name: "Kenyon Sadiq", position: "TE", team: "NYJ" },
  { rank: 198, name: "Troy Franklin", position: "WR", team: "DEN" },
  { rank: 199, name: "Isaac TeSlaa", position: "WR", team: "DET" },
  { rank: 200, name: "Rashod Bateman", position: "WR", team: "BAL" },
  { rank: 201, name: "Shedeur Sanders", position: "QB", team: "CLE" },
  { rank: 202, name: "Terrance Ferguson", position: "TE", team: "LAR" },
  { rank: 203, name: "Darnell Mooney", position: "WR", team: "NYG" },
  { rank: 204, name: "Keenan Allen", position: "WR", team: "IND" },
  { rank: 205, name: "Emanuel Wilson", position: "RB", team: "SEA" },
  { rank: 206, name: "Jaydon Blue", position: "RB", team: "DAL" },
  { rank: 207, name: "Pat Freiermuth", position: "TE", team: "PIT" },
  { rank: 208, name: "Kaytron Allen", position: "RB", team: "WAS" },
  { rank: 209, name: "Cade Otton", position: "TE", team: "TB" },
  { rank: 210, name: "Cooper Kupp", position: "WR", team: "SEA" },
  { rank: 211, name: "Zachariah Branch", position: "WR", team: "ATL" },
  { rank: 212, name: "Antonio Williams", position: "WR", team: "WAS" },
  { rank: 213, name: "Germie Bernard", position: "WR", team: "PIT" },
  { rank: 214, name: "Jaylen Wright", position: "RB", team: "MIA" },
  { rank: 215, name: "Jack Bech", position: "WR", team: "LV" },
  { rank: 216, name: "Evan Engram", position: "TE", team: "DEN" },
  { rank: 217, name: "Ollie Gordon II", position: "RB", team: "MIA" },
  { rank: 218, name: "Chimere Dike", position: "WR", team: "TEN" },
  { rank: 219, name: "Justice Hill", position: "RB", team: "BAL" },
  { rank: 220, name: "David Njoku", position: "TE", team: "LAC" },
  { rank: 221, name: "Greg Dulcich", position: "TE", team: "MIA" },
  { rank: 222, name: "Keon Coleman", position: "WR", team: "BUF" },
  { rank: 223, name: "George Holani", position: "RB", team: "SEA" },
  { rank: 224, name: "Ted Hurst III", position: "WR", team: "TB" },
  { rank: 225, name: "Malachi Fields", position: "WR", team: "NYG" },
  { rank: 226, name: "Elic Ayomanor", position: "WR", team: "TEN" },
  { rank: 227, name: "Demond Claiborne", position: "RB", team: "MIN" },
  { rank: 228, name: "Isaiah Davis", position: "RB", team: "NYJ" },
  { rank: 229, name: "Chris Bell", position: "WR", team: "MIA" },
  { rank: 230, name: "Colby Parkinson", position: "TE", team: "LAR" },
  { rank: 231, name: "Tory Horton", position: "WR", team: "SEA" },
  { rank: 232, name: "Christian Kirk", position: "WR", team: "SF" },
  { rank: 233, name: "Ja'Kobi Lane", position: "WR", team: "BAL" },
  { rank: 234, name: "Devaughn Vele", position: "WR", team: "NO" },
  { rank: 235, name: "Ty Johnson", position: "RB", team: "BUF" },
  { rank: 236, name: "Elijah Sarratt", position: "WR", team: "BAL" },
  { rank: 237, name: "LeQuint Allen Jr.", position: "RB", team: "JAC" },
  { rank: 238, name: "Jordan James", position: "RB", team: "SF" },
  { rank: 239, name: "Chris Brooks", position: "RB", team: "GB" },
  { rank: 240, name: "Kaelon Black", position: "RB", team: "SF" },
  { rank: 241, name: "Mason Taylor", position: "TE", team: "NYJ" },
  { rank: 242, name: "Xavier Legette", position: "WR", team: "CAR" },
  { rank: 243, name: "Samaje Perine", position: "RB", team: "CIN" },
  { rank: 244, name: "Darius Slayton", position: "WR", team: "NYG" },
  { rank: 245, name: "Caleb Douglas", position: "WR", team: "MIA" },
  { rank: 246, name: "Tyquan Thornton", position: "WR", team: "KC" },
  { rank: 247, name: "Marvin Mims Jr.", position: "WR", team: "DEN" },
  { rank: 248, name: "Theo Johnson", position: "TE", team: "NYG" },
  { rank: 249, name: "Eli Stowers", position: "TE", team: "PHI" },
  { rank: 250, name: "DJ Giddens", position: "RB", team: "IND" },
  { rank: 251, name: "Trey Benson", position: "RB", team: "ARI" },
  { rank: 252, name: "Oscar Delp", position: "TE", team: "NO" },
  { rank: 253, name: "Cyrus Allen", position: "WR", team: "KC" },
  { rank: 254, name: "Devin Neal", position: "RB", team: "NO" },
  { rank: 255, name: "Malik Davis", position: "RB", team: "DAL" },
  { rank: 256, name: "Najee Harris", position: "RB", team: "NYG" },
  { rank: 257, name: "Brashard Smith", position: "RB", team: "KC" },
  { rank: 258, name: "Kaleb Johnson", position: "RB", team: "PIT" },
  { rank: 259, name: "Kyle Williams", position: "WR", team: "NE" },
  { rank: 260, name: "Emari Demercado", position: "RB", team: "KC" },
  { rank: 261, name: "Hollywood Brown", position: "WR", team: "PHI" },
  { rank: 262, name: "Brandon Aiyuk", position: "WR", team: "SF" },
  { rank: 263, name: "Seth McGowan", position: "RB", team: "IND" },
  { rank: 264, name: "Devin Singletary", position: "RB", team: "NYG" },
  { rank: 265, name: "Adam Randall", position: "RB", team: "BAL" },
  { rank: 266, name: "Mike Gesicki", position: "TE", team: "CIN" },
  { rank: 267, name: "Mack Hollins", position: "WR", team: "NE" },
  { rank: 268, name: "Kendre Miller", position: "RB", team: "NO" },
  { rank: 269, name: "Isaiah Bond", position: "WR", team: "CLE" },
  { rank: 270, name: "Trevor Etienne", position: "RB", team: "CAR" },
  { rank: 271, name: "Skyler Bell", position: "WR", team: "BUF" },
];

const rankByKey: Map<string, number> = new Map(REFERENCE_RANKINGS.map((r) => [normalizeName(r.name), r.rank]));

/** Real-list rank for a player, matched by normalized name. Null if he's not on the list. */
export function getReferenceRank(name: string): number | null {
  return rankByKey.get(normalizeName(name)) ?? null;
}

/** Whether a player (matched by name) appears on the real reference list at all. */
export function isInReferenceList(name: string): boolean {
  return rankByKey.has(normalizeName(name));
}
